/**
 * Builds the Manual Outreach Pack — the final operator-facing artifact used
 * immediately before a human manually contacts a clinic. Read-only: never
 * crawls, never calls an external API, never creates, mutates, or sends
 * anything. No outreach status changes and no review decision changes as a
 * result of calling this function, allowed or blocked.
 *
 * Core rule: every requested channel is validated through the existing
 * read-only outreach approval gate (`canPrepareOutreachForSend`,
 * lib/operations/outreach/approval-gate.ts) before its copy is ever
 * surfaced. That gate already enforces: clinic exists, outreach message
 * exists and belongs to the clinic, neither is do_not_contact, the message
 * is in a sendable state (draft/approved, never sent/rejected/ignored/
 * replied), and the clinic's *latest* human_review_decisions row is
 * "approved". This builder adds one more check the gate doesn't do itself:
 * that a resolved message's own `channel` actually matches what was
 * requested.
 *
 * - If every requested channel is blocked, no pack is built at all — the
 *   function returns `ok: false` and no copy is ever computed.
 * - If some but not all requested channels are blocked, a pack IS built
 *   (`status: "partial_blocked"`) but the blocked channel's section
 *   carries only the block reason — never copy.
 * - Copy is never freshly generated by this builder. It is always the
 *   verbatim `outreach_messages.body`/`subject`/`click_to_chat_url` of the
 *   exact row that passed the gate — what the operator reads here is
 *   guaranteed to be what was actually approved, not a re-derived
 *   approximation of it.
 */
import type { ClinicRepository } from "@/lib/operations/repositories/clinic-repository";
import type { CrawlRepository } from "@/lib/operations/repositories/crawl-repository";
import type { ExtractionRepository } from "@/lib/operations/repositories/extraction-repository";
import type { ScoreRepository } from "@/lib/operations/repositories/score-repository";
import type { OutreachRepository } from "@/lib/operations/repositories/outreach-repository";
import type { HumanReviewRepository } from "@/lib/operations/repositories/human-review-repository";
import type { OutreachMessageRecord, RepoErrorReason } from "@/lib/operations/repositories/types";
import { buildOperationalReport } from "@/lib/operations/report/build-operational-report";
import type { OperationalReport, ScoreDimensionKey } from "@/lib/operations/report/types";
import { canPrepareOutreachForSend } from "@/lib/operations/outreach/approval-gate";
import { SCORE_DIMENSION_LABELS_PT, SCORE_DIMENSION_ORDER } from "@/lib/score/calculate";
import type {
  ChannelApprovalResult,
  ManualOutreachChannel,
  ManualOutreachCopyAvailable,
  ManualOutreachCopyBlocked,
  ManualOutreachCopySection,
  ManualOutreachPack,
  ManualOutreachScreenshotReference,
  RiskFlag,
} from "./types";

export type ManualOutreachChannelRequest = "whatsapp" | "email" | "both";

export type BuildManualOutreachPackInput = {
  clinicId: string;
  /** Only valid when a single channel ("whatsapp" or "email") is requested — ambiguous, and refused, when channel is "both". */
  outreachMessageId?: string;
  /** Default "both". */
  channel?: ManualOutreachChannelRequest;
  /** Default false. Adds a pack-only annotation next to the copy; never rewrites the persisted body itself. */
  includeScoreInCopy?: boolean;
  /** Default false. Surfaces the screenshot's private storage path (never a public/signed URL) in the screenshots section. */
  includeScreenshotLinks?: boolean;
};

export type BuildManualOutreachPackDeps = {
  clinicRepo: ClinicRepository;
  crawlRepo: CrawlRepository;
  extractionRepo: ExtractionRepository;
  scoreRepo: ScoreRepository;
  outreachRepo: OutreachRepository;
  humanReviewRepo: HumanReviewRepository;
};

export type BuildManualOutreachPackResult =
  | { ok: true; pack: ManualOutreachPack }
  | {
      ok: false;
      reason: RepoErrorReason | "blocked" | "validation" | "missing_score";
      message: string;
      approvalGateResults: ChannelApprovalResult[];
    };

function requestedChannelsFrom(channel: ManualOutreachChannelRequest): ManualOutreachChannel[] {
  if (channel === "whatsapp") return ["whatsapp_manual"];
  if (channel === "email") return ["email"];
  return ["whatsapp_manual", "email"];
}

function latestByChannel(messages: OutreachMessageRecord[], channel: ManualOutreachChannel): OutreachMessageRecord | null {
  const matching = messages.filter((m) => m.channel === channel);
  if (matching.length === 0) return null;
  return matching.reduce((a, b) => (a.createdAt >= b.createdAt ? a : b));
}

async function resolveChannelMessage(
  channel: ManualOutreachChannel,
  explicitOutreachMessageId: string | undefined,
  clinicId: string,
  deps: BuildManualOutreachPackDeps,
): Promise<{ message: OutreachMessageRecord } | { blockedResult: ChannelApprovalResult }> {
  if (explicitOutreachMessageId) {
    const found = await deps.outreachRepo.getMessage(explicitOutreachMessageId);
    if (!found.ok) {
      return {
        blockedResult: {
          channel,
          status: "blocked",
          outreachMessageId: null,
          code: "outreach_message_not_found",
          reason: found.message,
        },
      };
    }
    if (found.value.channel !== channel) {
      return {
        blockedResult: {
          channel,
          status: "blocked",
          outreachMessageId: found.value.id,
          code: "outreach_message_wrong_channel",
          reason: `Outreach message ${found.value.id} has channel "${found.value.channel}", not "${channel}".`,
        },
      };
    }
    return { message: found.value };
  }

  const listResult = await deps.outreachRepo.listForClinic(clinicId);
  const messages = listResult.ok ? listResult.value : [];
  const latest = latestByChannel(messages, channel);
  if (!latest) {
    return {
      blockedResult: {
        channel,
        status: "blocked",
        outreachMessageId: null,
        code: "no_persisted_draft_for_channel",
        reason: `No persisted outreach draft found for channel "${channel}" — nothing to validate through the approval gate.`,
      },
    };
  }
  return { message: latest };
}

function screenshotReferenceFor(
  section: OperationalReport["screenshots"]["desktop"],
  includeScreenshotLinks: boolean,
): ManualOutreachScreenshotReference {
  return {
    status: section.status,
    assetId: section.assetId,
    storagePath: includeScreenshotLinks ? section.storagePath : null,
    capturedAt: section.capturedAt,
  };
}

function keyEvidenceSummaryFrom(report: OperationalReport): string[] {
  const summary: string[] = [];
  for (const key of SCORE_DIMENSION_ORDER as ScoreDimensionKey[]) {
    const first = report.evidenceByDimension[key][0];
    if (first) summary.push(`${SCORE_DIMENSION_LABELS_PT[key]}: ${first.reason}`);
  }
  return summary.length > 0 ? summary : ["Nenhuma evidência disponível para este score."];
}

function riskFlagsFor(
  report: OperationalReport,
  doNotContact: boolean,
  doNotContactReason: string | null,
  channelResults: ChannelApprovalResult[],
): RiskFlag[] {
  const flags: RiskFlag[] = [];

  if (doNotContact) {
    flags.push({
      code: "do_not_contact",
      severity: "high",
      message: doNotContactReason
        ? `Clinic is marked do_not_contact: ${doNotContactReason}`
        : "Clinic is marked do_not_contact.",
    });
  }

  if (report.websiteAnalyzed.crawlStatus === "failed") {
    flags.push({ code: "crawl_failed", severity: "high", message: "The most recent crawl job failed." });
  } else if (report.websiteAnalyzed.crawlStatus === "partial") {
    flags.push({
      code: "crawl_partial",
      severity: "medium",
      message: "The most recent crawl job only partially completed (page limit or fetch failures) — content may be incomplete.",
    });
  }

  if (!report.scoreSummary.available) {
    flags.push({ code: "missing_score", severity: "high", message: "No score is available for this clinic/crawl job." });
  } else if (report.scoreSummary.total !== null && report.scoreSummary.total < 50) {
    flags.push({
      code: "low_score",
      severity: "medium",
      message: `Digital presence score is low (${report.scoreSummary.total}/100) — review before contacting.`,
    });
  }

  if (report.screenshots.desktop.status === "missing" || report.screenshots.desktop.status === "capture_failed") {
    flags.push({ code: "missing_screenshot_desktop", severity: "info", message: "Desktop homepage screenshot is missing or failed to capture." });
  }
  if (report.screenshots.mobile.status === "missing" || report.screenshots.mobile.status === "capture_failed") {
    flags.push({ code: "missing_screenshot_mobile", severity: "info", message: "Mobile homepage screenshot is missing or failed to capture." });
  }

  if (report.extractedContentSummary.available && report.extractedContentSummary.requiresHumanReview) {
    flags.push({
      code: "requires_human_review",
      severity: "info",
      message: "Extracted content is flagged as requiring human review before commercial use.",
    });
  }

  for (const result of channelResults) {
    if (result.status === "blocked") {
      flags.push({
        code: "channel_blocked",
        severity: "high",
        message: `Channel "${result.channel}" is blocked and was excluded from this pack: ${result.reason}`,
      });
    }
  }

  return flags;
}

function operatorSummaryFor(report: OperationalReport, packStatus: "ready" | "partial_blocked"): string {
  const parts: string[] = [];
  parts.push(report.clinicIdentity.displayName);
  parts.push(
    report.scoreSummary.available
      ? `score ${report.scoreSummary.total}/100 (${report.scoreSummary.scoringVersion})`
      : "score indisponível",
  );
  parts.push(packStatus === "ready" ? "todos os canais solicitados aprovados" : "aprovação parcial — ver flags de risco");
  return `${parts.join(" — ")}. Envio permanece manual: nenhum canal foi enviado por este pacote.`;
}

function operatorChecklist(): string[] {
  return [
    "Nome da clínica confirmado.",
    "Website confirmado.",
    "Última decisão de revisão humana está approved.",
    "Approval gate passou para o(s) canal(is) usado(s).",
    "Copy de WhatsApp/e-mail revisada manualmente antes do envio.",
    "Nenhuma alegação de qualidade médica presente.",
    "Nenhuma alegação/depoimento inventado presente.",
    "Nenhuma linguagem de pressão ou urgência presente.",
    "Screenshots não anexados, a menos que aprovados manualmente.",
    "Operador enviará manualmente — este pacote não envia nada.",
    "Operador registrará o resultado após o envio.",
  ];
}

function postSendLoggingChecklist(): string[] {
  return [
    "Canal usado.",
    "Data/hora do envio.",
    "Nome/iniciais do operador.",
    "Resposta recebida: sim/não.",
    "Follow-up necessário: sim/não.",
    "Notas registradas fora deste pacote ou em um sistema de logging futuro (ver docs/technical/crawler-manual-outreach-pack.md — future work).",
  ];
}

export async function buildManualOutreachPack(
  input: BuildManualOutreachPackInput,
  deps: BuildManualOutreachPackDeps,
): Promise<BuildManualOutreachPackResult> {
  const channelRequest = input.channel ?? "both";
  if (channelRequest !== "whatsapp" && channelRequest !== "email" && channelRequest !== "both") {
    return {
      ok: false,
      reason: "validation",
      message: `Invalid --channel "${channelRequest}" — must be "whatsapp", "email", or "both".`,
      approvalGateResults: [],
    };
  }
  const requestedChannels = requestedChannelsFrom(channelRequest);
  const includeScoreInCopy = input.includeScoreInCopy ?? false;
  const includeScreenshotLinks = input.includeScreenshotLinks ?? false;

  if (input.outreachMessageId && requestedChannels.length > 1) {
    return {
      ok: false,
      reason: "validation",
      message: "--outreach-message-id can only be used with a single --channel (whatsapp or email), not both.",
      approvalGateResults: [],
    };
  }

  const clinicResult = await deps.clinicRepo.getClinic(input.clinicId);
  if (!clinicResult.ok) {
    return { ok: false, reason: clinicResult.reason, message: clinicResult.message, approvalGateResults: [] };
  }
  const clinic = clinicResult.value;

  const reportResult = await buildOperationalReport(
    { clinicId: input.clinicId, allowIncomplete: true },
    {
      clinicRepo: deps.clinicRepo,
      crawlRepo: deps.crawlRepo,
      extractionRepo: deps.extractionRepo,
      scoreRepo: deps.scoreRepo,
      outreachRepo: deps.outreachRepo,
    },
  );
  if (!reportResult.ok) {
    return { ok: false, reason: reportResult.reason, message: reportResult.message, approvalGateResults: [] };
  }
  const report = reportResult.report;
  const warnings = [...report.warnings];

  const latestDecisionResult = await deps.humanReviewRepo.getLatestDecisionForClinic(input.clinicId);
  const latestDecision = latestDecisionResult.ok ? latestDecisionResult.value : null;

  const channelResults: ChannelApprovalResult[] = [];
  const resolvedMessages = new Map<ManualOutreachChannel, OutreachMessageRecord>();

  for (const channel of requestedChannels) {
    const resolved = await resolveChannelMessage(channel, input.outreachMessageId, input.clinicId, deps);
    if ("blockedResult" in resolved) {
      channelResults.push(resolved.blockedResult);
      continue;
    }
    const gate = await canPrepareOutreachForSend(
      { clinicId: input.clinicId, outreachMessageId: resolved.message.id },
      { clinicRepo: deps.clinicRepo, outreachRepo: deps.outreachRepo, humanReviewRepo: deps.humanReviewRepo },
    );
    if (gate.allowed) {
      resolvedMessages.set(channel, resolved.message);
      channelResults.push({
        channel,
        status: "allowed",
        outreachMessageId: resolved.message.id,
        code: null,
        reason: gate.reason,
      });
    } else {
      channelResults.push({
        channel,
        status: "blocked",
        outreachMessageId: resolved.message.id,
        code: gate.code,
        reason: gate.reason,
      });
    }
  }

  const allowedChannels = channelResults.filter((r) => r.status === "allowed").map((r) => r.channel);
  if (allowedChannels.length === 0) {
    return {
      ok: false,
      reason: "blocked",
      message: "Manual outreach pack was not generated — the approval gate blocked every requested channel.",
      approvalGateResults: channelResults,
    };
  }

  const status: ManualOutreachPack["status"] = allowedChannels.length === requestedChannels.length ? "ready" : "partial_blocked";

  function copySectionFor(channel: ManualOutreachChannel): ManualOutreachCopySection | null {
    if (!requestedChannels.includes(channel)) return null;
    const result = channelResults.find((r) => r.channel === channel)!;
    if (result.status === "blocked") {
      const blocked: ManualOutreachCopyBlocked = {
        channel,
        available: false,
        blockCode: result.code,
        blockReason: result.reason,
      };
      return blocked;
    }
    const message = resolvedMessages.get(channel)!;
    const internalScoreNote =
      includeScoreInCopy && report.scoreSummary.available
        ? `[Uso interno — não incluir na mensagem] Score: ${report.scoreSummary.total}/100 (${report.scoreSummary.scoringVersion}).`
        : null;
    const available: ManualOutreachCopyAvailable = {
      channel,
      available: true,
      outreachMessageId: message.id,
      outreachStatus: message.status,
      subject: message.subject,
      body: message.body,
      clickToChatUrl: message.clickToChatUrl,
      internalScoreNote,
    };
    return available;
  }

  const pack: ManualOutreachPack = {
    status,
    reviewRequired: true,
    generatedAt: report.generatedAt,
    disclaimer: report.disclaimer,

    operatorSummary: operatorSummaryFor(report, status),

    clinicIdentity: report.clinicIdentity,

    websiteAnalyzed: {
      crawlJobId: report.websiteAnalyzed.crawlJobId,
      requestedUrl: report.websiteAnalyzed.requestedUrl,
      normalizedOrigin: report.websiteAnalyzed.normalizedOrigin,
      crawlStatus: report.websiteAnalyzed.crawlStatus,
      pagesFetched: report.websiteAnalyzed.pagesFetched,
    },

    approvalStatus: {
      hasApprovedDecision: latestDecision?.decision === "approved",
      latestDecisionId: latestDecision?.id ?? null,
      decision: latestDecision?.decision ?? null,
      reviewer: latestDecision?.reviewer ?? null,
      reviewedAt: latestDecision?.reviewedAt ?? null,
    },

    approvalGateResults: channelResults,

    scoreSummary: {
      available: report.scoreSummary.available,
      total: report.scoreSummary.total,
      scoringVersion: report.scoreSummary.scoringVersion,
    },

    keyEvidenceSummary: keyEvidenceSummaryFrom(report),

    screenshots: {
      desktop: screenshotReferenceFor(report.screenshots.desktop, includeScreenshotLinks),
      mobile: screenshotReferenceFor(report.screenshots.mobile, includeScreenshotLinks),
    },

    riskFlags: riskFlagsFor(report, clinic.doNotContact, clinic.doNotContactReason, channelResults),

    whatsapp: copySectionFor("whatsapp_manual"),
    email: copySectionFor("email"),

    operatorChecklist: operatorChecklist(),
    postSendLoggingChecklist: postSendLoggingChecklist(),

    includeScoreInCopy,
    includeScreenshotLinks,

    warnings,
  };

  return { ok: true, pack };
}
