-- Atria crawler screenshots: private Supabase Storage bucket.
-- Additive only. Creates exactly one new Storage bucket row, idempotently
-- (on conflict do nothing) — no existing table, column, bucket, or policy
-- is altered or dropped.
--
-- Rationale: lib/operations/pipeline/screenshot-assets.ts already supports
-- uploading captured screenshots to a private bucket, but no bucket has
-- ever been provisioned in any environment this codebase has run against —
-- every screenshot captured so far (including the real SkinLaser capture
-- documented in docs/technical/crawler-second-real-domain-rehearsal.md)
-- exists only as "pending_storage" metadata, with no image bytes retained
-- anywhere. This migration provisions the bucket the uploader already
-- expects by name (DEFAULT_SCREENSHOT_STORAGE_BUCKET = "crawler-screenshots").
--
-- public = false: this bucket is never public. No public URL is ever
-- generated by any code in this repository (see
-- docs/technical/crawler-screenshot-storage-bucket.md for the structural
-- check that guarantees this). Only the service_role key (used exclusively
-- by the server-side crawler CLIs — never exposed to the browser) can read
-- or write objects in it; Supabase Storage denies anon/authenticated
-- access to a bucket with no storage.objects policies granting it, which
-- is the same "deny by default, service_role bypasses RLS" posture as
-- every table in this schema.
--
-- file_size_limit / allowed_mime_types: captured screenshots are always a
-- single PNG per capture (lib/crawler/screenshot-capture.ts always returns
-- contentType: "image/png"), so this bucket is scoped tightly to that —
-- 5 MB is comfortably above any real homepage screenshot's size.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('crawler-screenshots', 'crawler-screenshots', false, 5242880, array['image/png'])
on conflict (id) do nothing;
